### ISSUE TITLE
How did you get the word vectors?

### ISSUE THREAD

**Issue by zwy1996** [zhengye1995/BLC#1]
Hi, nice work!

I am sorry to bother you, when I read your paper, I did not find how you get the word vectors, did you follow the other work? could you please tell me the method?

Thanks very much!

**Comment by zhengye1995** [comment]
Hi,
   The word vectors are come from this work: https://github.com/salman-h-khan/PL-ZSD_Release.

Best regards

**Comment by zwy1996** [comment]
OK, I get it. 
Thank you for your quick response!
