### ISSUE TITLE
how do you get “word_w2v_withbg.txt"?

### ISSUE THREAD

**Issue by yechenzhi** [zhengye1995/BLC#4]
I know it's from "word_w2v.txt", and I already got "word_w2v.txt" from https://github.com/salman-h-khan/PL-ZSD_Release, but how to get “word_w2v_withbg.txt" for 48_17 and 65_15 separately?

**Comment by zhengye1995** [comment]
1. Calculate the average of the word vectors of all classes as the word vector of the background class
2.  Merge the word vector of background class with word_w2v.txt through placing it in the first of all word vectors to obtain word_w2v_withbg.txt

**Comment by yechenzhi** [comment]
Thanks.
